### ISSUE TITLE
Name collision

### ISSUE THREAD

**Issue by pavpanchekha** [herbie/herbie#1]
Hello!

I'm the lead developer for a roughly 6-year-old project called [Herbie](https://herbie.uwplse.org/). Since we've been growing the software and it now encompasses multiple repositories, we've decided to make a Github organization to track all of them in one place. Unfortunately, I see that the `herbie` organization name has already been taken.

Seeing as your organization was made recently, and the repository is empty, may I ask how attached you are to your chosen name? You registered it first, and its yours if you are, but otherwise would you be opposed to transferring it to our project?

(Also, apologies for reaching out via Github Issues, but unfortunately I couldn't find any other contact information.)

**Comment by merltron-pa** [comment]
Hey there, sorry for the very delayed answer - our dev team are busy growing Herbie (which is no longer empty). We had the repos in another orga but want to give the project its own orga. As to your question about whether we are attached to the name....well it was kind of a painful process to come up with one (I actually wrote an article about it: https://hackernoon.com/how-to-name-your-next-open-source-project-n8pv319u ) so we don't really want to change it again - sorry bout that.

**Comment by pavpanchekha** [comment]
Thanks for the response. Totally understand, and I wish you and your team the best!
